export const teams = {
  mclaren: {
    name: "McLaren",
    color: "#ff8700",
  },
  ferrari: {
    name: "Ferrari",
    color: "#ef1a2d",
  },
  mercedes: {
    name: "Mercedes",
    color: "#00a19c",
  },
  redbull: {
    name: "Red Bull",
    color: "#3671c6",
  },
};

export const drivers = [
  {
    id: "nor",
    number: 4,
    short: "NOR",
    name: "Lando Norris",
    team: "mclaren",
    basePace: 91,
    rainSkill: 84,
    experience: 82,
  },
  {
    id: "pia",
    number: 81,
    short: "PIA",
    name: "Oscar Piastri",
    team: "mclaren",
    basePace: 92,
    rainSkill: 80,
    experience: 74,
  },
  {
    id: "lec",
    number: 16,
    short: "LEC",
    name: "Charles Leclerc",
    team: "ferrari",
    basePace: 91,
    rainSkill: 86,
    experience: 86,
  },
  {
    id: "ham",
    number: 44,
    short: "HAM",
    name: "Lewis Hamilton",
    team: "ferrari",
    basePace: 89,
    rainSkill: 96,
    experience: 99,
  },
  {
    id: "rus",
    number: 63,
    short: "RUS",
    name: "George Russell",
    team: "mercedes",
    basePace: 88,
    rainSkill: 88,
    experience: 85,
  },
  {
    id: "ant",
    number: 12,
    short: "ANT",
    name: "Kimi Antonelli",
    team: "mercedes",
    basePace: 85,
    rainSkill: 78,
    experience: 60,
  },
  {
    id: "ver",
    number: 1,
    short: "VER",
    name: "Max Verstappen",
    team: "redbull",
    basePace: 95,
    rainSkill: 98,
    experience: 94,
  },
  {
    id: "had",
    number: 6,
    short: "HAD",
    name: "Isack Hadjar",
    team: "redbull",
    basePace: 84,
    rainSkill: 79,
    experience: 58,
  },
];

export const tracks = [
  {
    id: "interlagos",
    flag: "BR",
    name: "GP de São Paulo",
    rainChance: 0.46,
    chaosBase: 0.58,
    teamBias: {
      mclaren: 1.02,
      ferrari: 0.98,
      mercedes: 1.04,
      redbull: 1.0,
    },
    characteristics: ["reta dos boxes curta", "miolo travado", "subida forte no setor final"],
    note: "Interlagos costuma embaralhar estratégia, tráfego e clima.",
  },
  {
    id: "silverstone",
    flag: "GB",
    name: "GP da Grã-Bretanha",
    rainChance: 0.38,
    chaosBase: 0.5,
    teamBias: {
      mclaren: 1.05,
      ferrari: 0.98,
      mercedes: 1.03,
      redbull: 0.99,
    },
    characteristics: ["curvas longas de alta", "sequência Maggots-Becketts", "pouca tração lenta"],
    note: "Alta velocidade com vantagem para carros fortes em curvas longas.",
  },
  {
    id: "monaco",
    flag: "MC",
    name: "GP de Mônaco",
    rainChance: 0.12,
    chaosBase: 0.28,
    teamBias: {
      mclaren: 0.99,
      ferrari: 1.06,
      mercedes: 0.98,
      redbull: 1.01,
    },
    characteristics: ["ruas estreitas", "curvas lentas", "baixíssima chance de ultrapassagem"],
    note: "Poucas ultrapassagens: largada pesa muito no resultado.",
  },
  {
    id: "spa",
    flag: "BE",
    name: "GP da Bélgica",
    rainChance: 0.5,
    chaosBase: 0.62,
    teamBias: {
      mclaren: 1.0,
      ferrari: 0.99,
      mercedes: 1.0,
      redbull: 1.06,
    },
    characteristics: ["reta Kemmel longa", "Eau Rouge/Raidillon", "volta longa e clima instável"],
    note: "Spa combina pista longa, velocidade e chuva imprevisível.",
  },
  {
    id: "singapore",
    flag: "SG",
    name: "GP de Singapura",
    rainChance: 0.32,
    chaosBase: 0.7,
    teamBias: {
      mclaren: 1.01,
      ferrari: 1.04,
      mercedes: 0.99,
      redbull: 0.98,
    },
    characteristics: ["circuito de rua", "muitas curvas de baixa", "muro perto e safety car provável"],
    note: "Circuito de rua com safety cars e alta chance de confusão.",
  },
  {
    id: "bahrain",
    flag: "BH",
    name: "GP do Bahrein",
    rainChance: 0.03,
    chaosBase: 0.35,
    teamBias: {
      mclaren: 1.0,
      ferrari: 1.02,
      mercedes: 0.99,
      redbull: 1.04,
    },
    characteristics: ["retas fortes", "frenagens pesadas", "tração na saída de curva"],
    note: "Pouca chuva: o caos depende mais de ritmo e estratégia.",
  },
];
